apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soccer-agent-workshop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fhswf/soccer-agent.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: soccer-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
