apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wm2026-ingress
  namespace: soccer-agent
  annotations:
    traefik.frontend.passHostHeader: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  tls:
    - hosts:
        - wm2026.fh-swf.cloud
  rules:
    - host: wm2026.fh-swf.cloud
      http:
        paths:
          - path: /langflow
            pathType: Prefix
            backend:
              service:
                name: langflow
                port:
                  number: 7860
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mcp-server
                port:
                  number: 9000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: mcp-server
                port:
                  number: 9000
          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: mcp-server
                port:
                  number: 9000
          - path: /mcp
            pathType: Prefix
            backend:
              service:
                name: mcp-server
                port:
                  number: 9000
