apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soccer-agent
resources:
  - chromadb-deployment.yaml
  - mcp-server-deployment.yaml
  - langflow-deployment.yaml
  - ingress.yaml
  - news-scraper-cronjob.yaml
  - openai-api-key-sealed-secret.yaml
  - create_user.yaml
images:
  - name: ghcr.io/fhswf/soccer-agent/mcp-server
    newTag: 0.8.1
  - name: ghcr.io/fhswf/soccer-agent/data-pipeline
    newTag: 1.1.0
