apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: soccer-agent
data:
  config.yaml: |
    model_list:
      - model_name: gpt-4o
        litellm_params:
          model: gemini/gemini-1.5-pro
          api_key: "os.environ/GEMINI_API_KEY"
      - model_name: text-embedding-3-small
        litellm_params:
          model: gemini/text-embedding-004
          api_key: "os.environ/GEMINI_API_KEY"
    general_settings:
      master_key: "sk-litellm-master-key-2026"
