---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openai-api-key
  namespace: soccer-agent
spec:
  encryptedData:
    OPENAI_API_KEY: AgBj0/EkYUdH9t0LxIzhStl3kFnZoe7CP3s7gOFYZC3RUp11qvGVvfF9jmMMItQOH9mVzC5SfYguYhwkEWY54qn3+LaNsBPOvyPVtY+9hFfYzvtjlPwMtQxnQtWLP6x1O5SF2cDT1gL9Bsaobb9zKLIRXGJax+Mcd81hxxVhTbVisi0JnBMSDsuK7l9GrHyxVWuZuYcxV65taQ1QnqN59TLfMT680aL0rbSVBtvA9W7JRMYZnIfWKkaGLOo8HybKFB2nE+rdbYqdVK/+F+cjKeqYyf9kuXOf40fxIGVfULAFH2wf8rd2TwS/5Daqw4K37wWj2CHsCOxSJBlSUUCQrBsYp9D4XiVeklHINMCqCPX8qjxfFxYHxXBXSo3759iDcFdhOvpWD5/1T2ctbEZ/dbq3qLsMSRflozMUnXyKwpbsF85AwBI7vlKS5kKQliFRRpsCcMf9rYiHtVAujjML7+AC/1XlWgfFWURji/Hj8ZT9ntOl9uAb1XvcvyhVZlDoOCBChDFPcB6njIqfswSVD8J/0tZHAWDeGtfmfx2Aib6G2BFTs6MFi5wD/m17TWxQ4gwzI5B8hfFqKgisApyb7sdpMzYl/zpphRK+AdJV8XshUYM9FjVIpmkTwBjubBxci+YkRCrRHP8EYk21Ecid6GILDkgxBLrfSjCmH06wM0jjZrCdO+H3LujNp/xoYmlFyLCUDePeoj8Nhu996rjqpwV1aSclbYlO/On7
  template:
    metadata:
      name: openai-api-key
      namespace: soccer-agent
